# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

//1

package main

import "fmt"

var base, expoente int

func potencia(x int, n int) int {
    if n == 0 {
        return 1
    }
    return x * potencia(x, n-1)
}

func main() {
    fmt.Print("Digite a base e o expoente: ")
    fmt.Scan(&base, &expoente)
    resultado := potencia(base, expoente)
    fmt.Println("Resultado:", resultado)
}

//2
package main

import "fmt"

var valores = [5]int{10, 20, 30, 40, 50}

func adicao(nums []int) int {
    if len(nums) == 0 {
        return 0
    }
    return nums[0] + adicao(nums[1:])
}

func main() {
    resultado := adicao(valores[:])
    fmt.Println(resultado)
}